id: "webpod"
kind: "Pod"
apiVersion: "v1"
metadata:
  name: nginx-multideployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webnginx
    spec:
    containers: 
    - name: "webpod8085"
      image: "nginx"
      ports: 
      - containerPort: 80
        hostPort: 8085
    - name: "webpod8086"
      image: "nginx"
      ports: 
      - containerPort: 80
        hostPort: 8086
