id: "webpod"
kind: "Pod"
apiVersion: "v1beta1"
desiredState: 
  manifest: 
    id: "webpod"
    containers: 
      - name: "webpod8085"
        image: "nginx"
        ports: 
          - containerPort: 80
            hostPort: 8085
      - name: "webpod8086"
        image: "nginx"
        ports: 
          - containerPort: 80
            hostPort: 8086
labels: 
  name: "web"
